#include "include/url_launcher_elinux/url_launcher_elinux_plugin.h"

#include <flutter/basic_message_channel.h>
#include <flutter/encodable_value.h>
#include <flutter/plugin_registrar.h>
#include <flutter/standard_message_codec.h>
#include <gio/gio.h>
#include <glib.h>

#include <memory>
#include <string>
#include <thread>

namespace url_launcher_elinux {

namespace {

// Pigeon channel names generated by url_launcher_linux's messages.g.dart. We
// answer these directly so the upstream UrlLauncherLinux Dart side works
// unchanged on elinux. Keep these in sync with the url_launcher_linux version
// pinned in pubspec.lock.
constexpr char kCanLaunchChannel[] =
    "dev.flutter.pigeon.url_launcher_linux.UrlLauncherApi.canLaunchUrl";
constexpr char kLaunchChannel[] =
    "dev.flutter.pigeon.url_launcher_linux.UrlLauncherApi.launchUrl";

// Lomiri URL Dispatcher (current UBports). DispatchURL(url, package).
constexpr char kLomiriName[] = "com.lomiri.URLDispatcher";
constexpr char kLomiriPath[] = "/com/lomiri/URLDispatcher";
constexpr char kLomiriIface[] = "com.lomiri.URLDispatcher";
// Pre-Lomiri name still present on older Ubuntu Touch images.
constexpr char kCanonicalName[] = "com.canonical.URLDispatcher";
constexpr char kCanonicalPath[] = "/com/canonical/URLDispatcher";
constexpr char kCanonicalIface[] = "com.canonical.URLDispatcher";

// Pulls the single string argument out of a pigeon request. Pigeon wraps the
// args in a list, so the message is EncodableList{ EncodableValue(url) }.
const std::string* FirstStringArg(const flutter::EncodableValue& message) {
  const auto* list = std::get_if<flutter::EncodableList>(&message);
  if (!list || list->empty()) return nullptr;
  return std::get_if<std::string>(&(*list)[0]);
}

// A pigeon success reply is a one-element list wrapping the return value.
flutter::EncodableValue SuccessReply(flutter::EncodableValue value) {
  return flutter::EncodableValue(
      flutter::EncodableList{std::move(value)});
}

// Tries the url-dispatcher D-Bus service under the given well-known name.
// Returns true if the daemon accepted the URL for dispatch.
bool TryUrlDispatcher(GDBusConnection* conn, const char* name, const char* path,
                      const char* iface, const std::string& url) {
  GError* err = nullptr;
  GVariant* reply = g_dbus_connection_call_sync(
      conn, name, path, iface, "DispatchURL",
      g_variant_new("(ss)", url.c_str(), ""),
      /*reply_type=*/nullptr, G_DBUS_CALL_FLAGS_NONE,
      /*timeout_msec=*/5000, /*cancellable=*/nullptr, &err);
  if (reply) {
    g_variant_unref(reply);
    return true;
  }
  if (err) {
    g_warning("url_launcher_elinux: %s DispatchURL failed: %s", name,
              err->message);
    g_error_free(err);
  }
  return false;
}

// Desktop fallback (also works under a plain GIO session): hand the URI to the
// default registered handler. Mirrors what url_launcher_linux does natively.
bool TryGioDefault(const std::string& url) {
  GError* err = nullptr;
  gboolean ok = g_app_info_launch_default_for_uri(url.c_str(),
                                                   /*context=*/nullptr, &err);
  if (!ok && err) {
    g_warning("url_launcher_elinux: g_app_info_launch_default_for_uri failed: %s",
              err->message);
    g_error_free(err);
  }
  return ok;
}

// Last-resort fallback: spawn xdg-open if present on PATH.
bool TryXdgOpen(const std::string& url) {
  const char* argv[] = {"xdg-open", url.c_str(), nullptr};
  GError* err = nullptr;
  gboolean ok = g_spawn_async(
      /*working_directory=*/nullptr, const_cast<gchar**>(argv),
      /*envp=*/nullptr, G_SPAWN_SEARCH_PATH, /*child_setup=*/nullptr,
      /*user_data=*/nullptr, /*child_pid=*/nullptr, &err);
  if (!ok && err) {
    g_warning("url_launcher_elinux: xdg-open failed: %s", err->message);
    g_error_free(err);
  }
  return ok;
}

// Opens a URL, preferring the Ubuntu Touch URL dispatcher (which routes to the
// right app, e.g. Morph for http/https), then falling back to generic GIO /
// xdg-open for desktop elinux targets. Returns an empty string on success or a
// human-readable reason on failure (matching url_launcher_linux's contract,
// where launchUrl returns an error string).
std::string LaunchUrl(const std::string& url) {
  GError* err = nullptr;
  GDBusConnection* conn =
      g_bus_get_sync(G_BUS_TYPE_SESSION, /*cancellable=*/nullptr, &err);
  if (conn) {
    bool ok =
        TryUrlDispatcher(conn, kLomiriName, kLomiriPath, kLomiriIface, url) ||
        TryUrlDispatcher(conn, kCanonicalName, kCanonicalPath, kCanonicalIface,
                         url);
    g_object_unref(conn);
    if (ok) return std::string();
  } else if (err) {
    g_warning("url_launcher_elinux: session bus unavailable: %s", err->message);
    g_error_free(err);
  }

  if (TryGioDefault(url)) return std::string();
  if (TryXdgOpen(url)) return std::string();
  return "No URL handler available (url-dispatcher, GIO and xdg-open all failed)";
}

}  // namespace

class UrlLauncherElinuxPlugin : public flutter::Plugin {
 public:
  static void RegisterWithRegistrar(flutter::PluginRegistrar* registrar);
  UrlLauncherElinuxPlugin() = default;
  ~UrlLauncherElinuxPlugin() override = default;

  UrlLauncherElinuxPlugin(const UrlLauncherElinuxPlugin&) = delete;
  UrlLauncherElinuxPlugin& operator=(const UrlLauncherElinuxPlugin&) = delete;
};

// static
void UrlLauncherElinuxPlugin::RegisterWithRegistrar(
    flutter::PluginRegistrar* registrar) {
  const auto* codec = &flutter::StandardMessageCodec::GetInstance();

  // canLaunchUrl(url) -> bool. We can't cheaply probe handler availability, so
  // report support optimistically (the actual launch falls back across several
  // mechanisms). Replies synchronously.
  auto can_launch_channel =
      std::make_unique<flutter::BasicMessageChannel<flutter::EncodableValue>>(
          registrar->messenger(), kCanLaunchChannel, codec);
  can_launch_channel->SetMessageHandler(
      [](const flutter::EncodableValue& message,
         const flutter::MessageReply<flutter::EncodableValue>& reply) {
        reply(SuccessReply(flutter::EncodableValue(true)));
      });

  // launchUrl(url) -> String? (null on success, error string on failure).
  // Dispatch off the platform thread: a stuck session bus must not freeze UI.
  auto launch_channel =
      std::make_unique<flutter::BasicMessageChannel<flutter::EncodableValue>>(
          registrar->messenger(), kLaunchChannel, codec);
  launch_channel->SetMessageHandler(
      [](const flutter::EncodableValue& message,
         const flutter::MessageReply<flutter::EncodableValue>& reply) {
        const std::string* url = FirstStringArg(message);
        if (!url) {
          // Pigeon error envelope: [code, message, details].
          reply(flutter::EncodableValue(flutter::EncodableList{
              flutter::EncodableValue("INVALID_ARGS"),
              flutter::EncodableValue("Missing url argument"),
              flutter::EncodableValue()}));
          return;
        }
        std::thread([u = *url, reply]() {
          std::string error = LaunchUrl(u);
          if (error.empty()) {
            reply(SuccessReply(flutter::EncodableValue()));  // null -> success
          } else {
            reply(SuccessReply(flutter::EncodableValue(error)));
          }
        }).detach();
      });

  // SetMessageHandler registers the handler on the messenger, which outlives
  // these channel objects, so we can let them drop. Keep them owned by the
  // plugin all the same for symmetry / future use.
  registrar->AddPlugin(std::make_unique<UrlLauncherElinuxPlugin>());
  // Channels are intentionally leaked into the registered handlers' lifetime;
  // release so the unique_ptrs don't unregister on scope exit.
  can_launch_channel.release();
  launch_channel.release();
}

}  // namespace url_launcher_elinux

void UrlLauncherElinuxPluginRegisterWithRegistrar(
    FlutterDesktopPluginRegistrarRef registrar) {
  static auto* plugin_registrar = new flutter::PluginRegistrar(registrar);
  url_launcher_elinux::UrlLauncherElinuxPlugin::RegisterWithRegistrar(
      plugin_registrar);
}
